# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=20, unique=True)),
                ('hebrew_name', models.CharField(max_length=20, unique=True)),
                ('transliterated_name', models.CharField(max_length=20, unique=True)),
                ('sortkey', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['sortkey'],
            },
        ),
        migrations.CreateModel(
            name='Parasha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=40, unique=True)),
                ('hebrew_name', models.CharField(max_length=40, unique=True)),
                ('transliterated_name', models.CharField(max_length=40, unique=True)),
                ('notes', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'ordering': ['english_name'],
            },
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_chapter', models.PositiveSmallIntegerField()),
                ('start_verse', models.PositiveSmallIntegerField()),
                ('end_chapter', models.PositiveSmallIntegerField()),
                ('end_verse', models.PositiveSmallIntegerField()),
                ('start_sortkey', models.PositiveIntegerField()),
                ('end_sortkey', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bytes.Book')),
                ('parasha', models.ManyToManyField(to='bytes.Parasha')),
            ],
            options={
                'ordering': ['start_sortkey'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, unique=True)),
                ('hebrew_word', models.CharField(max_length=100, unique=True)),
                ('transliterated_word', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('sortkey', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bytes.Book')),
            ],
            options={
                'ordering': ['english_word'],
            },
        ),
    ]
