# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bytes', '0001_initial'), ('bytes', '0002_auto_20160623_2037'), ('bytes', '0003_auto_20160624_0655')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=20, unique=True)),
                ('hebrew_name', models.CharField(max_length=20, unique=True)),
                ('transliterated_name', models.CharField(max_length=20, unique=True)),
                ('sortkey', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parasha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=40, unique=True)),
                ('hebrew_name', models.CharField(max_length=40, unique=True)),
                ('transliterated_name', models.CharField(max_length=40, unique=True)),
                ('notes', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_chapter', models.PositiveSmallIntegerField()),
                ('start_verse', models.PositiveSmallIntegerField()),
                ('end_chapter', models.PositiveSmallIntegerField()),
                ('end_verse', models.PositiveSmallIntegerField()),
                ('start_sortkey', models.PositiveIntegerField()),
                ('end_sortkey', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bytes.Book')),
                ('parasha', models.ManyToManyField(to='bytes.Parasha')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, unique=True)),
                ('hebrew_word', models.CharField(max_length=100, unique=True)),
                ('transliterated_word', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('word_location', models.ManyToManyField(to='bytes.Word_Location')),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['sortkey']},
        ),
        migrations.AlterModelOptions(
            name='parasha',
            options={'ordering': ['english_name']},
        ),
        migrations.AlterModelOptions(
            name='portion',
            options={'ordering': ['start_sortkey']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['english_word']},
        ),
        migrations.AlterField(
            model_name='parasha',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['transliterated_word']},
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_location',
        ),
        migrations.AddField(
            model_name='word',
            name='book',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='bytes.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='chapter',
            field=models.PositiveSmallIntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='sortkey',
            field=models.PositiveIntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='verse',
            field=models.PositiveSmallIntegerField(default=999),
            preserve_default=False,
        ),
    ]
