# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0002_auto_20160623_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_location',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['transliterated_word']},
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_location',
        ),
        migrations.AddField(
            model_name='word',
            name='book',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='bytes.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='chapter',
            field=models.PositiveSmallIntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='sortkey',
            field=models.PositiveIntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='verse',
            field=models.PositiveSmallIntegerField(default=999),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Word_Location',
        ),
    ]
