# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0002_auto_20160624_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('sortkey', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bytes.Book')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='location',
            field=models.ManyToManyField(to='bytes.Location'),
        ),
    ]
