# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0007_auto_20160625_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='description',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
