# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0008_auto_20160626_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='id',
        ),
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
