# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0009_auto_20160704_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='location',
        ),
    ]
