# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0010_remove_word_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='location',
            field=models.ManyToManyField(to='bytes.Location'),
        ),
    ]
