# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 21:17
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0012_auto_20160811_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='xyzzy', editable=False, populate_from='english_word'),
            preserve_default=False,
        ),
    ]
