# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('sortkey', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=20)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('hebrew_text', models.CharField(max_length=2000)),
            ],
        ),
    ]
