# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bible',
        ),
    ]
